### ISSUE TITLE
CocoaPods downloads old version of the library

### ISSUE THREAD

**Issue by pacowong99** [richardtop/CalendarKit#110]
I'm a beginner in Swift and this is the first time I'm using a library so I'm sorry if this is a stupid question. 
I installed CalendarKit into my Xcode project and I had a few errors from the compiler. Although I can fix most of them, there are 2 that I don't know how to get rid of. Could someone please help and see how I could remove these errors? Thank you so much! 

<img width="1118" alt="screen shot 2017-10-25 at 4 21 25 pm" src="https://user-images.githubusercontent.com/11673896/32021180-a6bc054a-b9a0-11e7-8f84-e0078786f16a.png">
<img width="1119" alt="screen shot 2017-10-25 at 4 21 14 pm" src="https://user-images.githubusercontent.com/11673896/32021181-a6ce9174-b9a0-11e7-8587-1b9b71b09ddb.png">

**Comment by richardtop** [comment]
Hi, could you please specify your Swift version and post your `podfile.lock` file here?

**Comment by pacowong99** [comment]
Yes, I am using Swift 4.0. 
[Podfile.lock.zip](https://github.com/richardtop/CalendarKit/files/1416243/Podfile.lock.zip)

**Comment by richardtop** [comment]
Seems that CocoaPods are pulling the old version of the CalendarKit, the last Swift 3 release to be exact.

To fix the issue run this command in the same directory as your `podfile`:
```
pod update CalendarKit
```

Your issue should be resolved.

**Comment by pacowong99** [comment]
I just ran the command and the problem still exists. 
<img width="697" alt="screen shot 2017-10-25 at 6 45 42 pm" src="https://user-images.githubusercontent.com/11673896/32027012-b6d60930-b9b4-11e7-8ef6-8843db369e50.png">

**Comment by richardtop** [comment]
Try updating CocoaPods repository:
```
pod repo update
```

And then again, running this command:
```
pod update CalendarKit
```

Let's see, if it helps.

Alternatively, you may specify CocoaPods to pull code directly from this repository in your podfile, until this issue gets resolved.
```
pod 'CalendarKit', :git => 'https://github.com/richardtop/CalendarKit.git'
```

**Comment by pacowong99** [comment]
I tried these commands but it didn't work. I tried installing CalendarKit on a fresh Xcode file and it worked perfectly for me. Is there anyway that I can remove the entire library and reinstall it fresh?

**Comment by pacowong99** [comment]
Hi I'm sorry. I just checked the fresh file. There was 22 warnings and errors in total and I ran the commands, it went to 3 warnings and 7 errors. The two original errors are here also. Thank you so much for your help on this! 
<img width="1072" alt="screen shot 2017-10-25 at 11 45 26 pm" src="https://user-images.githubusercontent.com/11673896/32034145-c2d1b732-b9de-11e7-89cd-772197987db7.png">

**Comment by richardtop** [comment]
Does writing this line in your podfile helps? It will make CocoaPods to pull library directly from the master branch of this repository, ignoring tags. This could be a temporary workaround.
```
pod 'CalendarKit', :git => 'https://github.com/richardtop/CalendarKit.git'
```

Also, could you post your project here (it could be the minimal project setup you've mentioned earlier).

**Comment by pacowong99** [comment]
I just tried that command and it worked for me! Thank you so so much for your help!

**Comment by richardtop** [comment]
I'm glad to hear that.
Which command did you enter? This will help me to investigate this issue in detail, as you are not the only one who faced it.

**Comment by pacowong99** [comment]
I typed in this command in the CocoaPods OS X app. 

`pod 'CalendarKit', :git => 'https://github.com/richardtop/CalendarKit.git'`

**Comment by richardtop** [comment]
Unfortunately, that's just a workaround. While you can continue to work with CalendarKit, it seems that there is some error in CocoaPods repository.

I'll leave this issue open for now.

**Comment by dastan801** [comment]
Hi
I want to put my own time. f.e from 10:00 to 18:00 and event's for this time
Please can you help?
